### PR TITLE
copy bootstrap during preStart instead of postStart

### PR DESCRIPTION
**Pull request by zendril**
#### PR Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] Chart Version bumped
- [x] CHANGELOG.md updated

**What this PR does / why we need it**:
Copying the bootstrap configs are currently wired into the postStart. They need to be in the preStart so that they are on the filesystem before artifactory starts up.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #
No github issue, but support.jfrog.com support ticket #: 100501

**Special notes for your reviewer**:
David Xu (JFrog) commented in the support ticket that this is indeed backwards behavior.

### CODE REVIEW

**Comment by zendril** [comment]
@jainishshah17 @eldada @rimusz

Take a look when you can. Addresses support.jfrog.com ticket 100501

**Comment by zendril** [comment]
> This is a good idea.
> Can you also add it to the `artifactory` chart?

Will do first thing tomorrow.

**Comment by zendril** [comment]
> This is a good idea.
> Can you also add it to the `artifactory` chart?

Done.

**Comment by jainishshah17** [comment]
@zendril Can you please resolve conflicts?

**Comment by zendril** [comment]
@jainishshah17 Done.

**Pull request merged**
