### PR TITLE
Support customisable Nginx kind

### LINKED ISSUE #541: Nginx as Daemonset
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Feature Request

**Version of Helm and Kubernetes**:
```
helm version
Client: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
```
```
k version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.1", GitCommit:"d647ddbd755faf07169599a625faf302ffc34458", GitTreeState:"clean", BuildDate:"2019-10-02T23:49:20Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.10-eks-825e5d", GitCommit:"825e5de08cb05714f9b224cd6c47d9514df1d1a7", GitTreeState:"clean", BuildDate:"2019-08-18T03:58:32Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:
artifactory-ha

**What you expected to happen**:
Have the ability in the helm chart to change the nginx deployment to a daemonset, this way it will automatically scale to the number of nodes we have in our cluster.

### PR DESCRIPTION
**Pull request by Avinashkvp**
#### PR Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] Chart Version bumped
- [ ] CHANGELOG.md updated
- [ ] Variables and other changes are documented in the README.md

**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #541 

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by eldada** [comment]
Thx @Avinashkvp . This is a nice idea for added availability. I like it.
1. Please update the `Chart.yaml` with a new version
2. Update the `CHANGELOG.md` with the changes in this new version

**Comment by danielezer** [comment]
Nice! Thanks for the contribution @Avinashkvp! Please also add an entry to the README with the new configuration option.
Other than that, looks good!

**Comment by danielezer** [comment]
Implemented in #635

**Comment by Avinashkvp** [comment]
Sorry i didn't notice the PR checklist, will do in future PR
Thanks All !

**Pull request closed without merging**
