### PR TITLE
[artifactory] resource constraints for "setup" initContainer of nginx deployment

### LINKED ISSUE #962: Add support of specifying resources for initContainers in nginx deployment and Artifactory statefulset
**Is this a request for help?**:

No

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

FEATURE REQUEST

**Version of Helm and Kubernetes**:

Kubernetes v1.16.8
Helm v3.2.3

**Which chart**:

Artifactory Version 9.5.3

**What happened**:

When a `ResourceQuota` is configured in the namespace, pods are not deployed because resources requests and limits must be specified.

**What you expected to happen**:

To be able to configure resources request and limits for init containers through `values.yaml` file.

**How to reproduce it** (as minimally and precisely as possible):

Configure a `ResourceQuota` with CPU and memory request and limits and install the Helm Chart.

**Anything else we need to know**:

### PR DESCRIPTION
**Pull request by andrewrothstein**
#### PR Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] Chart Version bumped
- [ ] CHANGELOG.md updated
- [ ] Variables and other changes are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[artifactory]`)

**What this PR does / why we need it**:
my cluster requires resource constraints on all containers

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

fixes #962

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by andrewrothstein** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by andrewrothstein** [comment]
Is there anyone out there?

**Comment by RobinDuhan** [comment]
Thanks for the PR, Andrew. We are checking, and will be taking this in next patch and it will be available in next couple of weeks, 784.x.

**Comment by oumkale** [comment]
Hi @andrewrothstein,

Kudos to you, Thank you so much for this PR.  

We have released this in Artifactory version `7.84.14`.

**Pull request closed without merging**
