### PR TITLE
Added parameter to enable users to disable running of privileged containers

### PR DESCRIPTION
**Pull request by sponte**
#### PR Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ x ] Chart Version bumped
- [ x ] CHANGELOG.md updated
- [ x ] Variables and other changes are documented in the README.md

By default, this HELM chart deploys elasticsearch pod. It also configures docker host kernel parameters
using a privileged initContainer. In some installations, you would not be allowed to run privileged 
containers, in which case you can disable docker host configuration by configuring following parameter:

```
--set elasticsearch.configureDockerHost=false
```

### CODE REVIEW

**Comment by chukka** [comment]
@sponte  Thanks for the PR 👍 

Can I bother you to do a extra thing 

Change the destination branch to be inbound-from-forks.(rebase if needed) We are now using a two stage contribution flow. Once merged, we'll take into master. (https://github.com/jfrog/charts#contributing-to-jfrog-charts)

**Comment by sponte** [comment]
Hello @chukka 

Thanks for your reply. There doesn't seem to be `inbound-from-forks` branch in your repo. There is `pre-unified-platform-inbound-from-forks` though.

**Comment by sponte** [comment]
Hmm, that didn't work so well. I'll move back to master. Please let me know what to do

**Comment by chukka** [comment]
@sponte Sorry, Can you please try now - Change the destination branch to inbound-from-forks

**Comment by chukka** [comment]
@sponte I did it for you :)

**Comment by sponte** [comment]
Updated the PR rolling version forward

**Comment by chukka** [comment]
@sponte Can you please rebase and bump the chart version in chart.yaml and CHANGELOG.md one last time

**Comment by chukka** [comment]
@sponte Can you please rebase and bump the chart version in chart.yaml and CHANGELOG.md one last time

**Comment by sponte** [comment]
Done, sorry for delay, did not get the notification

**Pull request merged**
