### PR TITLE
[artifactory-ha] Add support for providing priorityClassName in nginx deployment

### PR DESCRIPTION
**Pull request by AshutoshNirkhe**
Resolves issue https://github.com/jfrog/charts/issues/1164 

#### PR Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] Chart Version bumped
- [ ] CHANGELOG.md updated
- [ ] Variables and other changes are documented in the README.md
- [ ] Title of the PR starts with chart name (e.g. `[artifactory]`)

**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by AshutoshNirkhe** [comment]
recheckcla

**Comment by AshutoshNirkhe** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by AshutoshNirkhe** [comment]
recheckcla

**Comment by eldada** [comment]
Thx @AshutoshNirkhe .
You are still missing 
- Chart Version bumped
- CHANGELOG.md updated

Please add these changes to your PR. These also fail the CI.

**Pull request closed without merging**
