### PR TITLE
[artifactory-ha] set as version value after the last colon

### PR DESCRIPTION
**Pull request by malamin**
#### PR Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] Chart Version bumped
- [x] CHANGELOG.md updated
- [x] Title of the PR starts with chart name (e.g. `[artifactory]`)

**What this PR does / why we need it**: incorrect value is set as a chart version when images are downloaded from DNS containing the port number, which makes helm deployment impossible without fixing the chart with kustomize
 (e.g. in case of 'test.jfrog.io:8085/example:123' in the artifactory-ha statefulset the version is set as '8085/example' instead of '123')

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by malamin** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by malamin** [comment]
recheck

**Comment by oumkale** [comment]
Hi @malamin,

Thank you reporting this issue, we have taken this internally. 
We will fix this in upcoming release and update you

**Comment by dosilyoun** [comment]
image
Looks like the fix was release with version 107.84.16

**Comment by chukka** [comment]
fixed via #1907

**Pull request closed without merging**
