### PR TITLE
add toggles for http/https nginx service

### LINKED ISSUE #526: Artifactory in-accessible when spun up using AWS ELB Load Balancer
**Is this a request for help?**: No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Helm and Kubernetes**:
```
Client: &version.Version{SemVer:"v2.15.2", GitCommit:"8dce272473e5f2a7bf58ce79bb5c3691db54c96b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.15.1", GitCommit:"cf1de4f8ba70eded310918a8af3a96bfe8e7683b", GitTreeState:"clean"}

Kubernetes EKS 1.14
```

**Which chart**: `artifactory-ha`

**What happened**: 
When using an AWS Load Balancer, classic or network, nginx starts but fails to serve content. 

**What you expected to happen**:
By specifying [the supported annotations](https://kubernetes.io/docs/concepts/cluster-administration/cloud-providers/#load-balancers), I can use an Amazon Load Balancer to front my nginx deployment and serve content via HTTP and/or HTTPS

**How to reproduce it** (as minimally and precisely as possible):
Stand up an Artifactory deployment with the following nginx service annotations:

```
nginx:
  service:
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
      service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:xx-xxxx-x:xxxxxxxxx:xxxxxxx/xxxxx-xxxx-xxxx-xxxx-xxxxxxxxx # replace this
```

**Anything else we need to know**:

* If you create the service using the `http` backend protocol, you'll be unable to access Artifactory via HTTPS because you'll be attempting to hit port 443 using the TCP protocol. 
* If you create the service using the `https` backend protocol, all of the instances will be marked as OutOfService because the health check will attempt to connect to port 80 (the port automatically selected for the health check) using the TLS protocol. 
* It would be great if we could select whether or not we want to serve up port 443.

### PR DESCRIPTION
**Pull request by andrewhertog**
#### PR Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] Chart Version bumped
- [x] CHANGELOG.md updated
- [x] Variables and other changes are documented in the README.md

**What this PR does / why we need it**:
There is a kubernetes bug: https://github.com/kubernetes/kubernetes/issues/83070 which screws up the listeners on the ELB. We manually overroad the nginx service values to disable the http listener. This PR brings our manual change into compliance with your chart.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #526 

**Special notes for your reviewer**:
@amithins @danielezer @eldada @rimusz

### CODE REVIEW

**Comment by andrewhertog** [comment]
@eldada I think the postgres pod in the e2e tests is broken. I can't check the Travis CI build, but when I run the `make mac` locally, the postgres pod fails to start with the following fatal error: `FATAL:  could not open relation mapping file "global/pg_filenode.map": No such file or directory`

**Comment by eldada** [comment]
> @eldada I think the postgres pod in the e2e tests is broken. I can't check the Travis CI build, but when I run the `make mac` locally, the postgres pod fails to start with the following fatal error: `FATAL: could not open relation mapping file "global/pg_filenode.map": No such file or directory`

The postgresql pod is part of the official postgresql chart we use. Nothing special on our side...

**Comment by eldada** [comment]
> This breaks compatibility for the previous values. I don’t think we can do that. @eldada WDYT?

You are right @danielezer . 

@andrewhertog - can you leave the old config (with a deprecation note) along the new config?

**Comment by andrewhertog** [comment]
> > This breaks compatibility for the previous values. I don’t think we can do that. @eldada WDYT?
> 
> You are right @danielezer .
> 
> @andrewhertog - can you leave the old config (with a deprecation note) along the new config?

Does bumping this to a minor release make more sense than a patch then?

**Comment by eldada** [comment]
> > > This breaks compatibility for the previous values. I don’t think we can do that. @eldada WDYT?
> > 
> > 
> > You are right @danielezer .
> > @andrewhertog - can you leave the old config (with a deprecation note) along the new config?
> 
> Does bumping this to a minor release make more sense than a patch then?

I'd leave it as a patch.

**Comment by andrewhertog** [comment]
Alright, i've added backwards compatibility. I've just added back the old values, and used an if/else to determine to use them or not. If both are there, it will use the new ones over the old ones.

Do i need to add a note in the README.md about deprecation too?

**Pull request merged**
