### PR TITLE
Don't merge - [artifactory] Allow securityContext to be removed from statefulset with flag

### LINKED ISSUE #1075: Remove runAsUser and fsGroup
**Is this a request for help?**: No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Feature Request

As per ticket #139759 from support.

When running the helm chart, the following lines are show up, no matter what I do:

```
      securityContext:
         runAsUser: 1030
         fsGroup: 1030
```
They show up twice in the resulting manifest.

This is not something that we can do in Openshift - you cannot runAsUser. Removing them is necessary to have the pod even spin up. There is no way to do this using helm values (that I have been able to find). Please add an option to remove these lines.

### PR DESCRIPTION
**Pull request by seansund**
- Adds artifactory.excludeSecurityContext flag to values, defaulted to false
- Adds condition around securityContext block in artifactory-statefulset to exclude if artifactory.excludeSecurityContext is true

#### PR Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] Chart Version bumped
- [x] CHANGELOG.md updated
- [x] Variables and other changes are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[artifactory]`)

**What this PR does / why we need it**:

This PR exposes a flag in the values.yaml to remove the securityContext block. It has been created as "excludeSecurityContext" and defaulted to `false` to preserve the current default behavior. The securityContext block is removed to allow the chart to install properly on OpenShift clusters.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

fixes #1075 

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by seansund** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by seansund** [comment]
recheckcla

**Comment by chukka** [comment]
@seansund Thanks for the contribution ! Can you please raise this for artifactory-ha chart too

**Comment by chukka** [comment]
@seansund Reminder !

**Comment by chukka** [comment]
@seansund Looks good, although we would prefer to see it set the other way around where we have a `setSecurityContext` with a default value of `true` ? WDYT @seansund @peters95 @rahulsadanandan

**Comment by rahulsadanandan** [comment]
@seansund 
we had a discussion internally about this. Can you please make the required changes in the pr
1) Instead of `excludeSecurityContext: false` can you add
```yaml
  ## By default, the Artifactory StatefulSet is created with a securityContext that sets the `runAsUser` and the `fsGroup` to the `artifactory.uid` value.
  ## If you want to disable the securityContext for the Artifactory StatefulSet, set this tag to false
  setSecurityContext: true
```
And the corresponding logic in statefulset
2) Also please remove the changes in the readme (as we already added a note in values.yaml). Also, this is because we will soon be moving all our documentation to confluence.
3) Add the same for artifactory-ha if possible.
4) rebase and fix the conflicts.

I tried adding some of the changes, but don’t have write access to your repo
cc @chukka @peters95 @eldada

**Comment by seansund** [comment]
> @seansund
> we had a discussion internally about this. Can you please make the required changes in the pr
> 
> 1. Instead of `excludeSecurityContext: false` can you add
> 
> ```yaml
>   ## By default, the Artifactory StatefulSet is created with a securityContext that sets the `runAsUser` and the `fsGroup` to the `artifactory.uid` value.
>   ## If you want to disable the securityContext for the Artifactory StatefulSet, set this tag to false
>   setSecurityContext: true
> ```
> 
> And the corresponding logic in statefulset
> 2) Also please remove the changes in the readme (as we already added a note in values.yaml). Also, this is because we will soon be moving all our documentation to confluence.
> 3) Add the same for artifactory-ha if possible.
> 4) rebase and fix the conflicts.
> 
> I tried adding some of the changes, but don’t have write access to your repo
> cc @chukka @peters95 @eldada

Sure thing. I'll make the change now

**Comment by chukka** [comment]
@seansund Thanks for quick turnaround, we would like to merge this PR to master with upcoming release of artifactory 7.12.x release  next week

**Review by chukka — APPROVED** [review]

**Review by rahulsadanandan — APPROVED** [review]
LGTM

**Review by eldada — APPROVED** [review]

**Pull request merged**
