### PR TITLE
Fix broken readme on Helm Hub

### PR DESCRIPTION
**Pull request by SimonAlling**
#### PR Checklist
- [x] Chart Version bumped
- [x] CHANGELOG.md updated

**What this PR does / why we need it**:

This PR is an attempt at fixing the readme, which is completely broken (see #657) on [Helm Hub](https://hub.helm.sh/charts/jfrog/artifactory) and [Kubeapps Hub](https://hub.kubeapps.com/charts/jfrog/artifactory). I suspect the problem is missing blank lines around fenced code blocks because

* breakage seems to occur at the start of such blocks (as seen by Ctrl+F'ing ``` `yaml``` or ``` `bash```);
* [GitHub Readme Instant Preview](https://github.com/joeyespo/grip) seems to produce well-formed output; and
* [Markdownlint](https://github.com/markdownlint/markdownlint) recommends blank lines around fenced code blocks.

The PR also adds (in separate commits) blank lines around headings and fixes a possible formatting error related to asterisks for good measure.

**Which issue this PR fixes**: #657 (hopefully)

**Special notes for your reviewer**:

I don't know how to mimic Helm Hub's Markdown rendering locally, so I don't know if this will fix the problem.

### CODE REVIEW

**Comment by SimonAlling** [comment]
So apparently the CI build failed because no chart changes were detected. :confused: 

```
The command "./test/lint-charts.sh || travis_terminate 1" exited with 0.
$ if cat tmp/lint.log | grep "No chart changes detected" > /dev/null; then
    echo "No chart changes detected, stopping TravisCI pipeline!"
    travis_terminate 0
fi

The command "if cat tmp/lint.log | grep "No chart changes detected" > /dev/null; then
    echo "No chart changes detected, stopping TravisCI pipeline!"
    travis_terminate 0
fi
" exited with 0.
```

**Comment by SimonAlling** [comment]
Does the CI build have to succeed before the PR can be merged? Do you understand why it failed and what could be done about it, @danielezer and @rimusz?

**Comment by danielezer** [comment]
Its ok @SimonAlling, the test just timed out. Since you only changed the README, it doesn't matter.

**Comment by danielezer** [comment]
Merged @SimonAlling, thanks for your contribution!

**Pull request merged**
