### PR TITLE
Don't Merge-[artifactory-ha] Add securityContext option to nginx container

### PR DESCRIPTION
**Pull request by louisblin**
#### PR Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] Chart Version bumped
- [x] CHANGELOG.md updated
- [ ] Variables and other changes are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[artifactory]`)

**What this PR does / why we need it**:

This is useful to set the `NET_BIND_SERVICE` capability on the nginx container, which is set on the `nginx` binary it contains. Workloads run with no capabilities by default in our clusters, so we need to be explicit about adding capabilities on containers that need it.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by louisblin** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by louisblin** [comment]
recheckcla

**Comment by louisblin** [comment]
Hi @chukka, you seem to be active in the repository lately. Any chance you could have a look please?

**Comment by chukka** [comment]
Thanks for contribution ! Can you add the same change for artifactory chart in same PR ?

Note : We will take this change internally and test and release it as part of next artifactory chart release.

**Comment by louisblin** [comment]
There you go, just added the same feature to the `artifactory` chart. Let me know if you need the commits squashed.

Also, is there an ETA on that next release?

**Comment by chukka** [comment]
squash helps  and ETA will be mostly couple of weeks

**Comment by louisblin** [comment]
Sounds good, and squashed. Thanks!

**Comment by louisblin** [comment]
Rebased on top of `master` to pick up 818453

**Comment by chukka** [comment]
@louisblin We already taken your changes and will be released in next few days

**Comment by louisblin** [comment]
Great, thanks !

**Comment by chukka** [comment]
Closing this as it got merged as part of #1426

**Pull request closed without merging**
