### PR TITLE
Check if there's an entry in the CHANGELOG for the current version in…

### LINKED ISSUE #46: Feature: Add a check that CHANGELOG has an entry for each new version
check that Chart.yaml’s `version` has an identical string in CHANGELOG in the format `## [1.2.3]`

### PR DESCRIPTION
**Pull request by danielezer**
… Chart.yaml and fail if there isn't such an entry

#### PR Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] Chart Version bumped
- [x] CHANGELOG.md updated
- [x] Variables and other changes are documented in the README.md

**What this PR does / why we need it**:
Check if there's an entry in the CHANGELOG for the current version set in Chart.yaml

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #
fixes #46

### CODE REVIEW

**Comment by danielezer** [comment]
@rimusz fixed.

**Comment by rimusz** [comment]
> @rimusz fixed.
> to be honest, I'm not sure how to test this feature without merging it, any thoughts?

make a chart change, don't add anything to the changelog, run `make lint` :)

**Comment by danielezer** [comment]
@rimusz will give it a shot tomorrow, thanks!

**Comment by danielezer** [comment]
yup @rimusz saw that. Working on a fix

**Comment by rimusz** [comment]
@danielezer can you combine to one `lint-charts-local.sh` and `lint-charts.sh` as `lint-charts.sh`
the difference there is in line `docker run --rm -v "$(pwd):/workdir" --workdir /workdir "$IMAGE_REPOSITORY:$IMAGE_TAG" ct lint --config /workdir/test/ct.yaml | tee tmp/lint.log`

**Comment by danielezer** [comment]
Sure @rimusz

**Comment by rimusz** [comment]
still seeing error `Error: No such container: ct`

**Comment by danielezer** [comment]
yeah, I’ll fix it tomorrow

**Comment by rimusz** [comment]
I got it fixed

**Pull request merged**
