### PR TITLE
[stable/artifactory-ha] Ability to define/apply Artifactory YAML Config

### LINKED ISSUE #1207: [artifactory-ha] FEATURE: Ability to define/apply Artifactory YAML Config
**Is this a request for help?**:
No

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
FEATURE REQUEST

I would like the ability to define [Artifactory YAML Configuration](https://www.jfrog.com/confluence/display/JFROG/Artifactory+YAML+Configuration) as a Value/ConfigMap and have the Chart automatically apply the configuration w/o having to bounce the Artifactory nodes (post-hook?).

**Version of Helm and Kubernetes**:
Kubernetes: `v1.17.7`
Helm: `v3.0.3`

**Which chart**:
`stable/artifactory-ha` Version `4.4.0`

**Anything else we need to know**:
This **maybe** possible using [this](https://github.com/jfrog/charts/tree/master/stable/artifactory-ha#provide-custom-configmaps-to-artifactory) but it would be fairly convoluted and would cause the Pods to bounce.

### PR DESCRIPTION
**Pull request by maxirus**
#### PR Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] Chart Version bumped
- [x] CHANGELOG.md updated
- [x] Variables and other changes are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[artifactory]`)

**What this PR does / why we need it**:
Adds the ability to define [Artifactory YAML Config](https://www.jfrog.com/confluence/display/JFROG/Artifactory+YAML+Configuration).

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #1207 

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by maxirus** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by rahulsadanandan** [comment]
@maxirus Thanks for the contribution, We would like to review and test this internally. Will update you back here if everything looks good.

**Comment by fl-max** [comment]
Why hasn't this been merged in the last few releases?

**Comment by chukka** [comment]
@maxirus Thanks for the PR, However , we had an internal discussion on this change and it seems like artifactory doesn't support this configuration via file system (raised a internal ticket -feature request with product team) as it currently only supports via YAML confg with REST API support.

However, we would like you to try this change with  `additionalResources` tag instead of helm hooks https://github.com/jfrog/charts/blob/master/stable/artifactory/values.yaml#L1437

If you have any questions, please reach to us for more info

**Comment by fl-max** [comment]
@chukka That's what this PR is doing; using the REST API to apply the yaml config.

**Comment by chukka** [comment]
@fl-max FYI, we don't want it to managed by REST API looking at other options like filesystem hence raised an internal enhancement with product team

**Comment by fl-max** [comment]
@chukka I'm not sure I follow the reasoning here. As I understand it, the current official way to manage this is through the REST API. This PR adds functionality, **today**, to Apply the YAML config via simple Helm Values.

I agree managing via filesystem is a better approach but that's a much larger initiative to implement. Also, I would assume that the REST API won't be going away anytime soon so iterating on this new feature in future, once filesystem support is added, should be a simple non-breaking change. Given this, I fail to see why JFrog wouldn't want to accept this PR and give its customers this new functionality today.

**Comment by chukka** [comment]
@fl-max As noted in one of my previous comments, you can use the `additionalResources` feature to define exactly what you suggested.
You simply create the `Job` resource for your env.

Historically, we found that removing features from the helm charts is very hard as many users couple their automation to a specific version and breaking that on a later release is something we try and avoid as much as possible.

Note : we already raised a feature request with product team internally to support out of box with filesystem , which will be simpler to use :) . Hope it helps

**Pull request closed without merging**
