### PR TITLE
Don't Merge [artifactory] add nodeport port

### PR DESCRIPTION
**Pull request by jmcrfp**
#### PR Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] Title of the PR starts with chart name (e.g. `[artifactory]`)

**What this PR does / why we need it**:
It adds the nodePort port configuration for artifactory helm chart to be possible to set a nodeport when the service type is nodePort

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by jmcrfp** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by jmcrfp** [comment]
recheckcla

**Comment by jmcrfp** [comment]
recheckcla

**Comment by chukka** [comment]
@jmcrfp Thanks for the contribution . Can you bump chart version in chart.yaml and changelog.md . Also, would you mind doing the same change for artifactory-ha chart in the same PR ?

**Comment by jmcrfp** [comment]
I've added the nodePort also to artifactory-ha and also to nginx template.
Bumped the charts versions.
Since by default people shouldn't change the node port, I couldn't find a good place to add it to values.yaml

**Review by srinivasgowda097 — APPROVED** [review]

**Review by eldada — CHANGES_REQUESTED** [review]
1. Can you please change `artifactory.nodePort` to `artifactory.service.nodePort`?
2. Can you change `nginx.nodePort` to `nginx.service.nodePort`
3. Can you add a commented out configuration block in `values.yaml`

**Comment by jmcrfp** [comment]
> 1. Can you please change `artifactory.nodePort` to `artifactory.service.nodePort`?
> 2. Can you change `nginx.nodePort` to `nginx.service.nodePort`
> 3. Can you add a commented out configuration block in `values.yaml`

I have changed as requested on 1 and 2. I also added the configuration requested on 3

**Review by eldada — APPROVED** [review]
LGTM

**Comment by chukka** [comment]
@jmcrfp Thanks, this feature will be available in artifactory  chart version

**Comment by chukka** [comment]
@jmcrfp  Sorry the delay, we internally reviewed and added it part of  7.23.x release (which will happen end of this month )

**Comment by chukka** [comment]
will be fixed as part of #1489

**Pull request closed without merging**
