### PR TITLE
[CHARTS] Adding CLA to chart repo

### PR DESCRIPTION
**Pull request by peters95**
#### PR Checklist

**What this PR does / why we need it**:

Adds a CLA to the repo for users to accept for contributions from the general public to sign the legal agreement first.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

Fixes all PRs coming from general public to enforce the CLA.

**Special notes for your reviewer**:

Needs to get merged prior to any other PRs like 1094 as contributors must sign the CLA prior to code merges.

### CODE REVIEW

**Review by vinayagg — CHANGES_REQUESTED** [review]
When I click on link, I get this message "This agreement is no longer accessible for signature. If you feel you have reached this page in error please contact the person who directed you to this page to sign the agreement."

**Review by jefferyfry — APPROVED** [review]
LGTM

**Comment by peters95** [comment]
Need to get the updated link to the CLA. Will reach out and update this.

**Comment by peters95** [comment]
Waiting for Eyal Ben Moshe to implement the CLA solution. Closing for now and posting a comment to the individual PR for them to sign that way similair to https://github.com/jfrog/artifactory-azure-devops-extension/pull/197

**Pull request closed without merging**
