### PR TITLE
[artifactory/ artifactory-ha] - Fix PostStartHookError

### PR DESCRIPTION
**Pull request by angegar**
#### PR Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] Chart Version bumped
- [x] CHANGELOG.md updated
- [x] Variables and other changes are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[artifactory]`)

**What this PR does / why we need it**:
Playing with the latest version of the Chart i encountered the following issue during the primary pod startup :

```shell
art-artifactory-ha-primary-0   0/1     PostStartHookError: command '/bin/bash -c echo;
' exited with 126:
```

The issue made me think i made something wrong with the PostStartHook however after verify my values.yaml file, i did no specify any command.  The current code always execute the PostStartHook and the command *echo;*  even if the user did not specify a command.

To prevent this behaviour i just move up the **{{- with .Values.artifactory.postStartCommand }}** above the **postStart** hook.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

I did not check if an issue is related.

**Special notes for your reviewer**:
I did not run this chart, i hope it will be done as part of the CI/CD pipeline.

### CODE REVIEW

**Comment by angegar** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by angegar** [comment]
checkcla

**Comment by chukka** [comment]
@angegar Thanks for the fix , Would you mind adding this to artifactory chart as well  in same PR ?

**Comment by chukka** [comment]
@angegar Reminder !

**Comment by rahulsadanandan** [comment]
@angegar 
For artifacotry-ha , we need to add the same implementation to `artifactory-node-statefulset.yaml` as well. 

Should we move {{- with .Values.artifactory.postStartCommand }} above `lifecycle:` tag  as we only have a postStart command there. Otherwise, it would come as empty tag in Kubernetes manifest file. 
What Do You Think? 
cc @chukka

**Comment by rahulsadanandan** [comment]
@angegar Can you please have a look at the comments?

**Comment by angegar** [comment]
hi @rahulsadanandan, i will try to complete this PR when i will have free time. 

And I will add the fiw to the artifactory chart.

Regarding lifecycle, we can surround by the with directive.

**Comment by angegar** [comment]
Does your pipeline test the chart ? because i did not do it

**Comment by rahulsadanandan** [comment]
@angegar  Sure. Thanks
Yes, our pipelines cover some ct tests. Also, we will do internal testing from our side before merge.

**Review by rahulsadanandan — APPROVED** [review]
LGTM

**Review by chukka — APPROVED** [review]

**Pull request merged**
