### PR TITLE
[xray]: Add the option to provide a precreated secret for master key

### PR DESCRIPTION
**Pull request by bnutt**
#### PR Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] Chart Version bumped
- [x] CHANGELOG.md updated
- [x] Variables and other changes are documented in the README.md

**What this PR does / why we need it**:
Adds the option to provide a precreated secret for the master key instead of providing secret through --set or values directly.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by bnutt** [comment]
> Please update `README.md` with the new key.

Updated README.md with the key and description. Please review at your convenience, thanks!

**Comment by danielezer** [comment]
@bnutt please add to the readme a line stating that the secret needs to have the “master-key”. It can be confusing to some users

**Comment by bnutt** [comment]
> @bnutt please add to the readme a line stating that the secret needs to have the “master-key”. It can be confusing to some users

@danielezer I've updated it to make a note of what key must be used in the secret, do you feel like the wording suffices?

**Comment by danielezer** [comment]
Yes @bnutt. Thanks, that’s great

**Comment by bnutt** [comment]
@eldada Could you have another look please :)

**Pull request merged**
