### PR TITLE
artifactory: Changed '-hex 16' -> '-hex 32' to agree with rest of doc

### PR DESCRIPTION
**Pull request by joe-sonrichard**
#### PR Checklist
**What this PR does / why we need it**:
Minor consistency fix. 
 - Table says keys are "**32** hex characters"
 - Instructions when creating [master key](https://github.com/jfrog/charts/blob/master/stable/artifactory/README.md#create-a-unique-master-key) and [join-key](https://github.com/jfrog/charts/blob/master/stable/artifactory/README.md#create-a-unique-join-key) say to create one with **32** hex characters.
 - Example command in table creates a key with **16** characters.

**Change:** command in table now creates a key with **32** characters.

### CODE REVIEW

**Comment by rimusz** [comment]
Thanks for the PR.
Please bump chart version and update changelog file as well.

**Comment by JfrogPrasanna** [comment]
@joe-sonrichard Thanks for the PR. The issue is that we need to align this  with the 6.x where the support for 16b so upgrade can  be seamless. We will  look at migration script to handle this and take your  PR as well. Thank you.

**Comment by joe-sonrichard** [comment]
Got it, I've bumped the changelog and version. I made the version on higher than I did in PR #672 since it sounds like that would be merged in sooner.

Also rebased off master.

**Comment by chukka** [comment]
Closing this and raised a PR https://github.com/jfrog/charts/pull/744

**Pull request closed without merging**
