### PR TITLE
[mission-control] Allow specifying uid for containers, custom annotations

### PR DESCRIPTION
**Pull request by JeroennC**
I am unsure how to bump chart version, or edit changelog. Could you provide me with guidelines?

About the change: Our cluster applies the `MustRunAsNonRoot` pod security policy, which does not allow containers with named users to spin up without specifying `runAsUser` with a numeric uid.
The mission control, insight scheduler, insight server & elasticsearch images used by this chart all have named users (`jfmc` and `elasticsearch` to be exact). Kubernetes would refuse to start them up with the error message "CreateContainerConfigError: container has runAsNonRoot and image has non-numeric user (elasticsearch), cannot verify user is non-root"

This change allows you to specify the numeric uid to avoid this issue.
I've also copied the custom annotations implementation from artifactory-ha.

#### PR Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] Chart Version bumped
- [ ] CHANGELOG.md updated
- [x] Variables and other changes are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[artifactory]`)

**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by JeroennC** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by chukka** [comment]
@JeroennC Thanks for the PR ! We already had an internal tracking  on this support,  will review this PR - This will be mostly included in next coming releases of Mission control chart

**Comment by chukka** [comment]
@JeroennC  Fixed with #1498  PR , can you please verify and let us know

**Comment by JeroennC** [comment]
Thanks @chukka ! We will make sure to move to the latest version soon.

**Pull request closed without merging**
