### PR TITLE
Fix the issue in the ingress path caused by using . inside of a range…

### PR DESCRIPTION
**Pull request by danielezer**
… clause instead of $

#### PR Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] Chart Version bumped
- [x] CHANGELOG.md updated
- [x] Variables and other changes are documented in the README.md

**What this PR does / why we need it**:
Fix the issue with the ingress path - https://github.com/jfrog/charts/pull/260/files#r267981799

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #
fixes #260 

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by jaspermarcus** [comment]
Thanks for fixing this so quickly. Is this fix meant to be available as part of chart `0.11.16`? I just tried pulling down the latest chart this morning, and it seemed to contain the readinessProbe changes that also bumped the chart version to `0.11.16`, but it seemed to be missing this change.

**Comment by rimusz** [comment]
two releases went with the same chart version `0.11.16`, the last one has this fix

**Comment by rimusz** [comment]
looks like it jenkins did not finish the job, triggered it again, now the chart has changes from this PR, sorry for confusion

**Comment by zendril** [comment]
Using helm template, this breaks ingress now with the following:

Error: render error in "artifactory-ha/templates/ingress.yaml": template: artifactory-ha/templates/ingress.yaml:32:26: executing "artifactory-ha/templates/ingress.yaml" at <.Values.ingress.path>: can't evaluate field Values in type interface {}

I can recreate it by setting `enabled: true` and uncommenting the hosts entry `- artifactory.domain.example`
```
ingress:
  enabled: true
  defaultBackend:
    enabled: true
  # Used to create an Ingress record.
  hosts:
    - artifactory.domain.example
```

Currently using helm 2.9.1, was this '. in a control structure scope change' changed in a newer version of helm perhaps?

I'll upgrade and do some testing, but might be worth calling out in the release notes or readme that this chart requires a minimum version of helm. Probably a decent thing to have in general anyways?

**Comment by zendril** [comment]
Confirmed. 2.13.1 works. 

@rimusz I see we have 
```
## Prerequisites Details

* Kubernetes 1.8+
* Artifactory HA license
```
At the top of our README.md.. does it make sense to also call out minimum helm version as well?

**Pull request merged**
