### PR TITLE
[artifactory][artifactory-ha] Prometheus ServiceMonitor optional and fluentd config updated

### PR DESCRIPTION
**Pull request by vovatikal**
…ed scrape annotations for metrics-service, fluentd config updated from jfrog/log-analytics-prometheus

#### PR Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] Chart Version bumped
- [x] CHANGELOG.md updated
- [x] Variables and other changes are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[artifactory]`)

**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

I have read the CLA Document and I hereby sign the CLA

### CODE REVIEW

**Comment by vovatikal** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by vovatikal** [comment]
recheckcla

**Comment by vovatikal** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by chukka** [comment]
@vovatikal Thanks for the contribution , We would like to test this internally (and merge to master in upcoming releases of the chart)

**Comment by chukka** [comment]
@vovatikal Sorry for the delay, We are testing this internally and planning to release this along with 7.12.x release, which may happen in couple of weeks

**Comment by chukka** [comment]
Hi @vovatikal  Unfortunately we won't be accepting this change.This was done following an internal discussion, not to have the log analytics resources included in our core helm chart.
The alternative working solution is added as part of another repository
https://github.com/jfrog/log-analytics-prometheus
We have added a working example there
https://github.com/jfrog/log-analytics-prometheus/blob/master/artifactory-values.yaml

**Pull request closed without merging**
