### PR TITLE
[Pipelines] Update dependency bitnami chart

### PR DESCRIPTION
**Pull request by rahulsadanandan**
#### PR Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] Chart Version bumped
- [x] CHANGELOG.md updated
- [x] Variables and other changes are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[artifactory]`)

**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Review by chukka — APPROVED** [review]

**Review by rimusz — APPROVED** [review]
LGTM

**Review by eldada — APPROVED** [review]

**Review by Khazinawaz — APPROVED** [review]
LGTM. 
Added documentation for using external postgresql

**Comment by Khazinawaz** [comment]
recheckcla

**Comment by Khazinawaz** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by peters95 — APPROVED** [review]

**Pull request merged**
