### PR TITLE
[artifactory-ha][artifactory][pipelines]Add support for ingress in k8s >= 1.22

### LINKED ISSUE #1407: Deprecated apiVersion for Ingress
**BUG REPORT**
Reopened #1315 

**Version of Helm and Kubernetes**:
Helm 3.5.2, Kubernetes v1.19.6-eks-49a6c0

**Which chart**:
artifactory-11.10.0

**What happened**:
The Ingress resource is not created with the right `apiVersion`.
Currently : `extensions/v1beta1`

**What you expected to happen**:
The Ingress resource should have `apiVersion` equal to `networking.k8s.io/v1beta1`

**How to reproduce it** (as minimally and precisely as possible):
Just install any artifactory chart using Helm 3 and kubernetes version >=1.14.0

**Anything else we need to know**:
Just as described in the original ticket, here is the issue: https://github.com/jfrog/charts/blob/master/stable/artifactory/templates/ingress.yaml#L6
Should not use deprecated `.Capabilities.KubeVersion.GitVersion` (since Helm 3).
`Capabilities.APIVersions.Has` should be used for API version Check (https://helm.sh/docs/chart_template_guide/builtin_objects)

### PR DESCRIPTION
**Pull request by yaron**
#### PR Checklist
- [x] Chart Version bumped
- [x] CHANGELOG.md updated
- [x] Title of the PR starts with chart name (e.g. `[artifactory]`)

**What this PR does / why we need it**:
This removes usage of the deprecated APIVersions for ingresses(if newer versions are supported) which will be removed in Kubernetes 1.22. Also this uses .Capabilities.APIVersions.Has instead of .Capabilities.KubeVersion.Version to check for availability of api versions.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: Fixes #1407

**Special notes for your reviewer**:
Tested artifactory-ha and artifactory on k8s 1.19.7 (with networking.k8s.io/v1/Ingress) and 1.18 (with networking.k8s.io/v1beta1, but not networking.k8s.io/v1/Ingress). I didn't test the pipeline chart.

### CODE REVIEW

**Comment by yaron** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by yaron** [comment]
recheckcla

**Comment by chukka** [comment]
@yaron Thanks for the PR , We would like to review and test this internally and mostly will be pushing this for next release of artifactory /pipelines in few weeks !

**Review by rimusz — APPROVED** [review]
LGTM

**Comment by chukka** [comment]
Update : This Change will be rolled out in 7.27.x artifactory charts(mostly end of this month)

**Comment by chukka** [comment]
Fixed in #1509

**Comment by yaron** [comment]
@chukka thanks for the work on this, but could you next time just note that you're not going to merge the PR but copy the work to your own commit? Maybe put a notice in the contributing part of the Readme? I feel like I wasted time on signing the CLA, keeping the branch up to date and monitoring this PR. Also I feel like I didn't get the credits for the work that I did.

I noticed that you did the same for other PRs, so probably needs to be a bit clearer in the Readme that external contributors will not be credited in commits.

**Comment by chukka** [comment]
@yaron  Thanks for reporting ! we will make sure all community PRs are acknowledged and credited , we will update our Readme to reflect this in upcoming 7.28.x release and also credit your contribution in changelog.

We appreciate your time and effort  on this

**Pull request closed without merging**
