### PR TITLE
[jfrog-platform] 10.8.0 release

### PR DESCRIPTION
**Pull request by chukka**
#### PR Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] Chart Version bumped
- [x] CHANGELOG.md updated
- [x] Variables and other changes are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[artifactory]`)

**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by pathob** [comment]
@chukka It's a little bit sad to see how you just pick changes made by community contributors into your own commits instead of just merging their pull requests. That's not a motivation to contribute more here.

**Comment by chukka** [comment]
@pathob  Thanks for reaching out ! We always wanted to recognise  and appreciate the efforts put forwarded by community members . Just wanted to clarify few things here 

we maintain two different  codebases one internally and another one on github . All the bugfixes/new features are internally tested and also our internal tests are more complex and tied to the product release lifecycle and then finally released  on github for customers. Hence, this approach is followed.

Also, we highlight the contribution in changelog  with pull requests , do you want to add your name as well to those pull request ?

Hope this helps !

**Comment by pathob** [comment]
@chukka I was thinking a long time whether and how to reply to this. Let me just add two statements.

1. Git is a distributed version control system that totally allows you to work with internal and external "code bases" and that also allows you to pull in external contributions into your internal "code base".

2. Merging pull requests is the best way to thank external contributors for their effort - closing their pull requests while cherry-picking their changes into own commits is probably the worst. It's not the case for my contribution, it was tiny and simple, but: Merged open source pull requests might be super important for developers in their career path, both as employees or freelancers.

**Comment by chukka** [comment]
@pathob Thanks for reaching out , we would like to re-evaluate this internally and come back

**Pull request merged**
