### PR TITLE
[artifactory][artifactory-ha] Add enablePathStyleAccess for aws-s3-v3 persistence type

### LINKED ISSUE #1234: [artifactory][artifactory-ha] Configuring the awsS3V3 binary store provider is missing enablePathStyleAccess
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**FEATURE REQUEST**

Currently the Artifactory HA chart allows you to [configure](https://github.com/jfrog/charts/blob/870ea8d7f500caae95bcece42574acecd7ee43ac/stable/artifactory-ha/values.yaml#L1021) the `aws-s3-v3` binary provider but (in my case) is missing one vital option (see JFrog [documentation](https://www.jfrog.com/confluence/display/JFROG/Configuring+the+Filestore#ConfiguringtheFilestore-AmazonS3OfficialSDKTemplate)), the `enablePathStyleAccess` property. This is due to using Minio instead of AWS S3 as the S3 implementation.

I require the `enablePathStyleAccess` property to be set to `true` to avoid DNS resolution issues where the bucket name is prefixed to the `endpoint`.

**Which chart**:

```
name: artifactory-ha
version: 4.4.2
appVersion: 7.10.2
```

### PR DESCRIPTION
**Pull request by donovanmuller**
#### PR Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] Chart Version bumped
- [x] CHANGELOG.md updated
- [ ] Variables and other changes are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[artifactory]`)

**What this PR does / why we need it**:

Adds the `enablePathStyleAccess` value to the `awsS3V3` [section](https://github.com/jfrog/charts/blob/870ea8d7f500caae95bcece42574acecd7ee43ac/stable/artifactory-ha/values.yaml#L1021).

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

fixes #1234

### CODE REVIEW

**Comment by donovanmuller** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by chukka — APPROVED** [review]

**Comment by chukka** [comment]
@donovanmuller Would you mind changing the changelog date to today's date for both charts  and also can you squash all your commits to a single one .

**Comment by chukka** [comment]
@donovanmuller Can you also fix the conflicts here

**Review by eldada — APPROVED** [review]

**Review by ronnyn — APPROVED** [review]

**Comment by chukka** [comment]
@donovanmuller You need to rebase and  bump chart versions in chart.yaml and changelog

**Comment by chukka** [comment]
I can do it for you, please hold on

**Review by peters95 — APPROVED** [review]
LGTM

**Pull request merged**
