### PR TITLE
[xray] Adding structured system yaml to allow for individual key/value overrides

### PR DESCRIPTION
**Pull request by nxf5025**
#### PR Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] Chart Version bumped
- [x] CHANGELOG.md updated
- [x] Variables and other changes are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[artifactory]`)

**What this PR does / why we need it**:

Allows users to add/overwrite parts of the textual representation of the system.yaml after template evaluation. This allows users to provide individual overrides for the default system.yaml without needing to copy and paste the whole config.

For example:

To add the configuration talked about in [this article](https://jfrog.com/help/r/xray-why-am-i-getting-a-total-bytes-limit-reached-error-when-indexing-a-package-in-xray) it's as easy adding it to the structuredSystemYaml:
```
xray:
  structuredSystemYaml:
    indexer:
      compress:
        RationLimit: 500
```

This would result in something like the following when fully rendered:
```
  system.yaml: |
    configVersion: 1
    contextualAnalysis:
      image: jfrog/xray-jas-contextual-analysis
      registry: releases-docker.jfrog.io
    exposures:
      container:
        image: jfrog/xray-jas-exposures
        registry: releases-docker.jfrog.io
    indexer:
      compress:
        RationLimit: 2000
    router:
      serviceRegistry:
        insecure: false
    shared:
      database:
        driver: org.postgresql.Driver
        type: postgresql
      jfrogUrl: http://artifactory.artifactory.svc.cluster.local:8082
      logging:
        consoleLog:
          enabled: true
```

**Special notes for your reviewer**:
Inspiration is from the Mimir Helm chart - https://github.com/grafana/mimir/pull/2100

If this gets accepted I will also be opening a similar PR for the Artifactory chart

### CODE REVIEW

**Comment by nxf5025** [comment]
**_I have read the CLA Document and I hereby sign the CLA_**

**Comment by nxf5025** [comment]
recheck

**Comment by chukka** [comment]
@nxf5025 Thanks for the PR ! we would like to review this internally and come back next week . I hope this much needed feature every one wants to try :) 

cc @eldada @rahulsadanandan

**Comment by chukka** [comment]
Update : we are planning to take this feature in coming weeks, if there are any changes required to this PR , we will let you know.

**Comment by nxf5025** [comment]
@chukka Awesome sounds good. As promised I have also opened the Artifactory PR with the same changes - https://github.com/jfrog/charts/pull/1848

**Comment by chukka** [comment]
**Update :** we are internally evaluating refactoring systemYaml in values.yaml and would like to take this PR as part of it in next quarter , Thanks for your patience !

**Comment by gregoryboue** [comment]
@chukka any news on the ETA ?

**Comment by Logeshwarsn** [comment]
@gregoryboue We are planning to take this feature in this quarter. And we will update you on the release date soon.

**Comment by gregoryboue** [comment]
@Logeshwarsn the end of the quarter is coming, any news on this feature ?

**Comment by gregoryboue** [comment]
@chukka @Logeshwarsn do you have any release date of this feature ?

**Comment by gregoryboue** [comment]
> @gregoryboue Due to other priorities, there has been a delay. We are now including this feature in the 3.95.x release, scheduled for May.

Hi, we are in may and the 3.96 has been released but this feature is not available, is it possible to have an ETA ?

**Pull request merged**
