### PR TITLE
[artifactory-ha] add connectionTimeout, and socketTimeout parameters for s3-storage-v3 Binary Provider

### PR DESCRIPTION
**Pull request by singhhema**
Included connectionTimeout and socketTimeout for provider id="remote-s3 and s3-storage-v3" , as suggested by jfrog Artifactory Team

#### PR Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] Title of the PR starts with chart name (e.g. `[artifactory]`)

**What this PR does / why we need it**:
This PR will add connectionTimeout, and  socketTimeout parameters for s3-storage-v3 Binary Provider,: which is suggested by JFrog artifactory team as a solution to improve performance and reduce timeout errors.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #
 there are so many timeouts  and the bad performance (e.g. CPU/Networking wise...) which are  tuning related (increase max connections pool and timeout values for the various binary providers) and are most likely rooted in your binarystore.xml configuration file

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by singhhema** [comment]
recheck

**Comment by singhhema** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by singhhema** [comment]
recheck

**Comment by singhhema** [comment]
I have read the CLA Document and I hereby sign the CLA.

**Comment by singhhema** [comment]
recheck

**Comment by singhhema** [comment]
recheck

**Comment by singhhema** [comment]
Can someone help? i guess workflow is broken.

**Comment by singhhema** [comment]
@chukka can you please help here to pass the prechecks for this PR?

**Comment by singhhema** [comment]
@danielezer @eldada @JfrogPrasanna @jfrogerann Please review this PR

**Comment by chukka** [comment]
@singhhema  Thanks for the PR , we would like to review this internally and come back

**Comment by singhhema** [comment]
@chukka how long this will take to review PR internally?

**Comment by chukka** [comment]
@singhhema we would like take this  PR internally (test and merge)  and will be mostly available in next release of artifactory , 7.41.x . No action is required from your side .

**Comment by gitta-jfrog** [comment]
Hi @singhhema, We discussed this request internally with our R&D, Support, and Product colleagues and decided not to implement this. 

The binarystore is part of JFrog Artifactory.  While we are trying to support most of the **common** properties of binarystore through the Helm Charts (Artifactory and Artifactory-HA), there are some properties that will not be supported through the Helm Charts. Adding these values to the S3V3 Provider, required us to implement the same in EVERY other provider in both charts.

Modification of "connectionTimeout" and "socketTimeout" are not common and should be done only in rare cases where needed. For situations like this, we maintain the ability to [pass the binarystore.xml as a secret](https://github.com/jfrog/charts/tree/master/examples/artifactory/binarystore).

I'm sorry that it took us a while to conclude the internal discussion.

Yarden
JFrog Support

**Pull request closed without merging**
