### PR TITLE
[mission-control] added init containter for external postgresql

### PR DESCRIPTION
**Pull request by vovatikal**
#### PR Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] Chart Version bumped
- [x] CHANGELOG.md updated
- [x] Variables and other changes are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[artifactory]`)

**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Review by chukka — CHANGES_REQUESTED** [review]
@vovatikal Thanks for the contribution ! Can you wrap the initcontainer   with  this condition `postgresql.enabled=false`

**Review by danielezer — APPROVED** [review]

**Comment by chukka** [comment]
@vovatikal We would like to test this internally before we can merge - Please give us atleast week's time for the same

**Comment by vovatikal** [comment]
@chukka any news?

**Comment by chukka** [comment]
> @chukka any news?

Please give us couple of days more :)

cc @rahulsadanandan

**Review by rahulsadanandan — APPROVED** [review]
Tested ,LGTM

**Review by eldada — APPROVED** [review]

**Review by chukka — APPROVED** [review]

**Comment by chukka** [comment]
@vovatikal Thanks for your time on this PR - We had a discussion internally and decided that we want to have a common single script (which will be invoked as init container for creation of schemas and users) for all products in upcoming releases. This is planned very soon, stay tuned.So decided not to merge this PR.

**Pull request closed without merging**
