### PR TITLE
added support for headless services

### PR DESCRIPTION
**Pull request by guptaarvindk**
#### PR Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] Chart Version bumped
- [x] CHANGELOG.md updated
- [x] Variables and other changes are documented in the README.md

**What this PR does / why we need it**:
added support for headless services

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by guptaarvindk** [comment]
@jainishshah17, I also have PR pending for postgressql, Once thats approved need to bump the dependency chart (postgres) version to 3.6.1, which is big jump. I will be submitting a new PR for that, but do you see any major issue with that?

**Comment by jainishshah17** [comment]
@guptaarvindk I will let @eldada Answer that.

**Comment by guptaarvindk** [comment]
> @guptaarvindk
> 
> * For the PR, please add this functionality to the `artifactory` chart as well. We try to keep them aligned. We plan on merging them eventually.
> * For the new postgesql version - will it support upgrading from existing version? what's the reason you want to use the new version?

Hi @eldada previous postgress chart was not having support for headless service which is required for us. I have added the support to latest version fo postgres chart.

**Comment by eldada** [comment]
Hi @guptaarvindk.
1. Please rebase and update this PR
2. I still need to know if this change supports upgrading from an older version of the postgresql chart?

**Comment by eldada** [comment]
@guptaarvindk - is this still relevant? If so, please address my previous comments. If not, can you close it?

**Comment by guptaarvindk** [comment]
Hi @eldada , sorry for no response for long. This got buried in long list of work. 

Regarding "supports upgrading from an older version of the postgresql chart". I have not bumped the postgres chart version in this. I just mentioned it for future requirement. This PR is only for clusterIp support for services.

**Comment by eldada** [comment]
Ok. Thx for the clarification @guptaarvindk .
Can you rebase and update the versions?

**Comment by guptaarvindk** [comment]
thanks @eldada , pushed the changes. Can you please review.

**Pull request merged**
