### PR TITLE
artifactory: Fixed: typo logabck.xml -> logback.xml

### PR DESCRIPTION
**Pull request by joe-sonrichard**
Context suggests it is always supposed to be `logback.xml` and that there is not another file, called `logabck.xml`, which is being referenced.

#### PR Checklist
**What this PR does / why we need it**:
Fixes a typo. Though minor, it could be confusing to someone if they see two different spellings and assume there are two files in play.

### CODE REVIEW

**Comment by rimusz** [comment]
Thanks for the PR.
Please bump chart version and update changelog file as well.

**Comment by joe-sonrichard** [comment]
Got it, I've bumped the changlog and version. First time I did that I found out version 9.0.25 had been taken so I had to change it again after re-basing off master. Used a force push to try to clean it up a bit.

**Comment by eldada** [comment]
@joe-sonrichard - can you rebase again and resolve conflict (another merge was just made). Thx in advance and sorry for the hassle.

**Comment by eldada** [comment]
I will fix this with #681 to save you the trouble.

**Pull request closed without merging**
