### PR TITLE
[pipelines] updates RBAC rules for Pipelines

### PR DESCRIPTION
**Pull request by Bharath92**
#### PR Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] Chart Version bumped
- [x] CHANGELOG.md updated
- [ ] Variables and other changes are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[artifactory]`)

**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by Bharath92** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by chukka — CHANGES_REQUESTED** [review]
#1385  needs to be merged first, Pls rebase Once #1385 is merged

**Review by eldada — APPROVED** [review]

**Review by rimusz — APPROVED** [review]
LGTM

**Comment by chukka** [comment]
@rahulnlb1  looks like this is breaking this build , please check 
```
          securityContext:
            allowPrivilegeEscalation: false
            runAsUser: 0
```

**Pull request closed without merging**
