### PR TITLE
chart: xray v0.5.4

### PR DESCRIPTION
**Pull request by rimusz**
* Add ci/test-values.yaml for minikube

### CODE REVIEW

**Comment by jainishshah17** [comment]
@rimusz Why are you removing MongoDB image tag?

**Comment by jainishshah17** [comment]
@rimusz there is a version diff. We use 3.6.3 and official MongoDB chart version 2.0.5 uses 3.6.4 
https://github.com/helm/charts/blob/c923b9d83f05707ce45440117f63050bb4aaedf7/stable/mongodb/values.yaml#L7.

@eldada are you ok bumping MongoDB version?

**Comment by eldada** [comment]
@jainishshah17 - I'm ok with this. I'm testing this to make sure. Will update here.

**Comment by eldada** [comment]
@rimusz - revert back to mongo 3.6.3 until we can properly test this.

**Comment by rimusz** [comment]
closing in favor of #61

**Pull request closed without merging**
