### PR TITLE
[ artifactory ]  Added metadata maxOpenConnections

### PR DESCRIPTION
**Pull request by DNewt**
#### PR Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] Chart Version bumped
- [x] CHANGELOG.md updated
- [x] Variables and other changes are documented in the README.md

**What this PR does / why we need it**:
This allows us to configure the amount of metadata database connections. 
Currently Access and Artifactory maxOpenConnections can be defined but not metadata. 

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by chukka** [comment]
@DNewt Thanks for PR !  can you please bump chart version and Also add changelog to take it forward

**Comment by DNewt** [comment]
Opps! Thought I had, will do now sorry

**Comment by chukka** [comment]
@DNewt  Looks like you missed out chart version bump in chart.yaml , Can you update PR

**Comment by DNewt** [comment]
Good catch, fixed

**Comment by DNewt** [comment]
Hmm before you approve it - is the "" around maxOpenConnections: "{{ .Values.metadata.database.maxOpenConnections }}" a problem? 

I noticed in our Artifactory config that access maxOpenConnections had quotes around its value, whereas the database maxOpenConnections value didn't. 

I have no clue if this has an impact overall 
```

    database:
        maxOpenConnections: {{ .Values.artifactory.database.maxOpenConnections }}
    access:
      database:
        maxOpenConnections: "{{ .Values.access.database.maxOpenConnections }}"
      {{- if .Values.access.database.enabled }}
        type: "{{ .Values.access.database.type }}"
        url: "{{ .Values.access.database.url }}"
        driver: "{{ .Values.access.database.driver }}"
        username: "{{ .Values.access.database.user }}"
        password: "{{ .Values.access.database.password }}"
      {{- end }}
    metadata:
      database:
        maxOpenConnections: "{{ .Values.metadata.database.maxOpenConnections }}"
```

**Comment by chukka** [comment]
@DNewt I would  prefer no quotes for numerical values - please refer [this](https://stackoverflow.com/questions/19109912/do-i-need-quotes-for-strings-in-yaml) for more Info 
Can you change access /metadata's maxOpenConnections to  without quotes in both artifactory and artifactory-ha charts

**Pull request merged**
