### PR TITLE
[artifactory][artifactory-ha] Change semverCompare checks to support hosted Kubernetes

### PR DESCRIPTION
**Pull request by ckoenig**
#### PR Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] Chart Version bumped
- [x] CHANGELOG.md updated
- [x] Title of the PR starts with chart name (e.g. `[artifactory]`)

**What this PR does / why we need it**:

The semverCompare checks for Ingress do not work as expected on hosted Kubernetes environments like GKE, since the check simply fails, c.f. helm/helm#3810.

### CODE REVIEW

**Comment by chukka** [comment]
@ckoenig Thanks for the PR, Can you please raise separate PRs for artifactory and pipelines ?

**Comment by ckoenig** [comment]
> @ckoenig Thanks for the PR, Can you please raise separate PRs for artifactory and pipelines ?

OK. I removed the changes for pipelines in this PR.

**Comment by ckoenig** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by rahulsadanandan** [comment]
@ckoenig We would test this internally and come back soon

**Review by rahulsadanandan — APPROVED** [review]
LGTM

**Review by chukka — APPROVED** [review]

**Review by chukka — APPROVED** [review]

**Pull request merged**
