### PR TITLE
Add the necessary nginx configuration for distribution to the replica…

### LINKED ISSUE #165: Add nginx configuration for distribution
**Is this a request for help?**:

NO

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

FEATURE REQUEST

**Version of Helm and Kubernetes**:
ALL

**Which chart**:
artifactory and artifactory-ha

**What happened**:
Missing nginx configuration for JFrog Enterprise plus platform, according to this guide:
https://www.jfrog.com/confluence/display/RTF/Artifactory+Enterprise+Plus
these two settings are missing:
```
{
  proxy_http_version 1.1;
  chunked_transfer_encoding on;
}
```
--

### PR DESCRIPTION
**Pull request by danielezer**
…tor configuration -

https://www.jfrog.com/confluence/display/RTF/Artifactory+Enterprise+Plus

#### PR Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] Chart Version bumped
- [x] CHANGELOG.md updated
- [x] Variables and other changes are documented in the README.md

**What this PR does / why we need it**:
Adds missing nginx configuration for distribution setup 

**Which issue this PR fixes** *
 fixes #165 

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by danielezer** [comment]
This will solve issue #165

**Comment by jainishshah17** [comment]
@danielezer @eldada Was this closed by mistake?

**Comment by danielezer** [comment]
@jainishshah17 no, I am not sure if this is needed. According to the documentation - https://www.jfrog.com/confluence/display/RTF/Artifactory+Enterprise+Plus - The two lines need to be added to the nginx configuration, but I'm not sure if they should be in the replicator virtual server configuration or in the artifactory virtual server. Do you have any thoughts about that? @eldada told me you are the expert I should ask :)

**Comment by jainishshah17** [comment]
If it is required for both Replicator and Artifactory then I think we should add it to `nginx.conf`. As per doc -> http://nginx.org/en/docs/http/ngx_http_core_module.html#chunked_transfer_encoding it is supported in `http` context as well. @eldada how about adding this to default nginx.conf that we distribute with nginx docker image?

**Pull request closed without merging**
