### PR TITLE
[artifactory][artifactory-ha] Enable Open Metrics support

### LINKED ISSUE #1232: [artifactory][artifactory-ha] Allow enabling open metrics API
**Is this a request for help?**: No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

**Version of Helm and Kubernetes**:

**Which chart**: artifactory & artifactory-ha

**What happened**:  As of Artifactory v7.7 it is possible to enable an open metrics API endpoint on Artifactory by adding some configuration to the system.yaml. The required configuration is documented here: https://www.jfrog.com/confluence/display/JFROG/Open+Metrics

**What you expected to happen**: I would like to be able to enable the metrics endpoint using helm values. Either using the existing `metrics.enabled` value, or one that is more specific.

**Anything else we need to know**:

### PR DESCRIPTION
**Pull request by donovanmuller**
#### PR Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] Chart Version bumped
- [x] CHANGELOG.md updated
- [x] Variables and other changes are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[artifactory]`)

**What this PR does / why we need it**: This PR adds a new chart property `artifactory.openMetrics.enabled` to enable/disable [Open Metrics support](https://www.jfrog.com/confluence/display/JFROG/Open+Metrics) in Artifactory 7.7+

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #1232

**Special notes for your reviewer**: There is an existing `metrics.enabled` chart property used for ["Prometheus Metrics"](https://github.com/jfrog/charts/tree/master/stable/artifactory-ha#prometheus-metrics). I was not sure if enabling this should also enable Open Metrics support (I.e. use the same `metrics.enabled` property to drive the value of the Artifactory System YAML property of `artifactory.metrics.enabled`) so have opted for a new property. Please advise...

### CODE REVIEW

**Comment by rahulsadanandan** [comment]
@donovanmuller Thanks for this contribution. We will have this tested internally and get back.

**Comment by rahulsadanandan** [comment]
@donovanmuller I have updated the values.yaml  and removed readme because we will be moving all documentation to confluence. Please review.
We will have this merged along with next app release in the coming weeks. Thanks

**Comment by donovanmuller** [comment]
@rahulsadanandan LGTM

**Review by rahulsadanandan — APPROVED** [review]
LGTM

**Review by eldada — APPROVED** [review]

**Review by chukka — APPROVED** [review]

**Pull request merged**
