### PR TITLE
Missing quote for ingress host names in all charts

### LINKED ISSUE #71: Missing quote for ingress host names in all charts
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

BUG REPORT
**Version of Helm and Kubernetes**:

**Which chart**:

All charts

**What happened**:

Charts are not compatible with ingres hosts names begining with '*', Helm complains about syntax

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

Ingress host names should be quoted like this:

```
  {{- range $host := .Values.ingress.hosts }}
  - host: {{ $host | quote }}
```

See how the ingress template is created with "helm create" command.

### PR DESCRIPTION
**Pull request by sebastien-prudhomme**
**What this PR does / why we need it**:

Enable using host names beginings with '*' in ingress

**Which issue this PR fixes**

fixes #71 

**Special notes for your reviewer**:

As it is a minor change, i didn't update the changelog and the version of all charts

### CODE REVIEW

**Comment by jainishshah17** [comment]
@sebastien-prudhomme Thank you for your contribution. Can you please update changelog as well.

**Comment by rimusz** [comment]
also all changed charts version needs a bump too

**Comment by eldada** [comment]
@sebastien-prudhomme 
It's ok, but needs CHANGELOG and version update for all charts.

**Comment by sebastien-prudhomme** [comment]
ok, version and changelog updated

**Pull request merged**
