### PR TITLE
[xray] Move postgresql values fields to correct place in Xray Helm chart

### PR DESCRIPTION
**Pull request by kristinnardal2**
Postgresql has both resources and nodeSelector under master and slave.
Having this in the incorrect place in the Values.yaml file makes it
confusing for people trying to use the chart.

#### PR Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] Chart Version bumped
- [x] CHANGELOG.md updated
- [x] Variables and other changes are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[artifactory]`)

**What this PR does / why we need it**:
This change is functionally a no-op change. It moves some default postgresql parameters to their correct places. Having the incorrect values is confusing for people deploying the chart because changing the values as they were documented wouldn't actually change anything in the final rendered manifest.

**Special notes for your reviewer**:
Artifactory, Artifactory-ha and mission-control also have this exact problem, I'll submit PRs for those as soon as we've finished this one.

### CODE REVIEW

**Comment by chukka** [comment]
@kristinnardal2  Thanks for contribution , Can you please rebase and update PR

**Comment by chukka** [comment]
@kristinnardal2  Can you please correctly rebase the PR with only your delta changes (looks like we have 85 files changed)

If you feel its easy to make your delta changes with new PR (please close this PR) and raise a new one

**Comment by kristinnardal2** [comment]
I might make a new change since I accidentally pushed all the changes instead of rebasing, I'll try to do this later today when I have time.

**Comment by chukka** [comment]
> I might make a new change since I accidentally pushed all the changes instead of rebasing, I'll try to do this later today when I have time.

Sure. Thanks

**Comment by kristinnardal2** [comment]
Replaced with #1005 

For some reason I originally moved the resources part of to master/slave. This was incorrect and I have reverted it in the new PR.

**Pull request closed without merging**
