### PR TITLE
[artifactory-ha] Only create certificate secret if Nginx is enabled

### PR DESCRIPTION
**Pull request by koalaty-code**
#### PR Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] Chart Version bumped
- [x] CHANGELOG.md updated
- [x] Title of the PR starts with chart name (e.g. `[artifactory]`)

**What this PR does / why we need it**:

This PR eliminates the creation of the Nginx TLS certificate when Nginx is disabled. #1271 changed the behavior to create the secret if `nginx.https.enabled`, which defaults to `true`. It seems redundant to need the following Helm values to disable all Nginx resources:
```yaml
nginx:
  enabled: false
  https:
    enabled: false
```

With this change in place, fully disabling Nginx will only require:
```yaml
nginx: 
  enabled: false
```

### CODE REVIEW

**Comment by koalaty-code** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by rahulsadanandan** [comment]
@koalaty-code 
Thanks for the PR, Would you mind doing the same changes for artifactory chart too in the same PR.
Note : We will plan to merge this PR to master along with the next artifactory app release in the coming weeks.
cc @chukka

**Review by rahulsadanandan — APPROVED** [review]
LGTM

**Review by rimusz — APPROVED** [review]
LGTM

**Review by eldada — APPROVED** [review]

**Comment by chukka** [comment]
@rahulsadanandan Bump appversion to 7.15.4

**Pull request merged**
