### PR TITLE
[jfrog-platform]Allow running the init DB container as a non-root user

### PR DESCRIPTION
**Pull request by pbecotte**
…matter if the db is actually running in the initdb container, for accessing it over the network (which is always the case) username/password is all that matters.

#### PR Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [X] Chart Version bumped
- [X] CHANGELOG.md updated
- [ ] Variables and other changes are documented in the README.md
- [X] Title of the PR starts with chart name (e.g. `[artifactory]`)

**What this PR does / why we need it**:
In an environment where root security contexts are forbidden, the init DB container will be rejected- but it isn't necessary anyway since postgres is being accessed over the network.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by chukka** [comment]
@pbecotte Thanks for the contribution  ! We will review/test it  and If every thing looks , we will take it to  upcoming releases ! 

can you also sign the CLA by just posting a Pull Request Comment !

**Comment by pbecotte** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by chukka** [comment]
we would like to include this fix  with upcoming release of artifactory 7.29.x in coming week(s)

**Comment by chukka** [comment]
sorry , missed this PR , I would like to take this in next release

**Comment by chukka** [comment]
Added part of #1625  PR

**Pull request closed without merging**
