### PR TITLE
Don't Merge [arttifactory] Fix for #1409 

### LINKED ISSUE #1409: [artifactory][artifactory-ha] filebeat-configmap.yaml needs different template
**Is this a request for help?**:
no
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
bug report

Wen activating metrics for artifactory a filebeat-configmap.yaml file will generate a configmap, but with the wrong name.
Changing the lines containing `{{ template "artifactory.name" . }}` to `{{ template "artifactory.fullname" . }}` will fix this (PR will be provided asap.)

**Version of Helm and Kubernetes**:

7.17.5 (1.20)

**Which chart**:

`artifactory` and `artifactory-ha`

**What happened**:

Wrong name for configmap is generated.

**What you expected to happen**:

Expect correct name for configmap to be generated.

**How to reproduce it** (as minimally and precisely as possible):

Just use metrics

**Anything else we need to know**:

I prepared a PR.

### PR DESCRIPTION
**Pull request by malagant**
#### PR Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [X] Chart Version bumped
- [x] CHANGELOG.md updated
- [ ] Variables and other changes are documented in the README.md
- [X] Title of the PR starts with chart name (e.g. `[artifactory]`)

**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #1409 

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by malagant** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by malagant** [comment]
recheckcla

**Comment by malagant** [comment]
recheckcla

**Comment by rahulsadanandan** [comment]
@malagant Thanks for this fix
I think there is one more reference, we need to change.
https://github.com/jfrog/charts/blob/master/stable/artifactory/templates/artifactory-statefulset.yaml#L744

**Comment by malagant** [comment]
Oh, yes. Just missed that one. Thank you. I'll check everything again and provide a commit.

**Comment by malagant** [comment]
@rahulsadanandan It seems that this was the only piece missing. Do you know why the checks fail, when in fact, they ran successfully?

**Comment by rahulsadanandan** [comment]
@malagant Sorry I forgot to mention we need to add the changelog entry as well. Otherwise, the linting charts would fail.
please refer here https://github.com/jfrog/charts/blob/master/stable/artifactory/CHANGELOG.md
for both artifactory and artifactory-ha

**Comment by malagant** [comment]
Sorry, my fault. It's my first PR. Next time ;)

**Comment by malagant** [comment]
Any chance that we find 3 approvers for this?

**Comment by chukka** [comment]
@malagant we would like to release this as part of 7.18.x artifactory release , we will take from here , No action is need from your side

**Comment by chukka** [comment]
@malagant  one small change   `app: {{ template "artifactory.name" . }}` to be aligned with other resources

**Comment by malagant** [comment]
> @malagant one small change `app: {{ template "artifactory.name" . }}` to be aligned with other resources

Sorry, I don't get it. Where should the change happen? Or did you already change it?

**Comment by chukka** [comment]
@malagant I already addressed it , will be part of 7.18.x release in next few days

**Comment by chukka** [comment]
PR changes are in #1419

**Comment by malagant** [comment]
I found out that these changes were rolled back with current 7.18.6 release? Any reasons for this?

**Comment by chukka** [comment]
@malagant  can you please check again , FYI - I set labels as below  (not fullname  just for backward compatibility)
```
labels:
    app: {{ template "artifactory-ha.name" . }}
```

**Pull request closed without merging**
