### PR TITLE
[xray] Fix containerSecurityContext with loggers in StatefulState template

### PR DESCRIPTION
**Pull request by jbblache**
#### PR Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] Chart Version bumped
- [x] CHANGELOG.md updated
- [x] Title of the PR starts with chart name (e.g. `[artifactory]`)

**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

Fix containerSecurityContext on loggers since we are in a range. The .Values.containerSecurityContext.enabled is not found and replaced. The "$" fixes the problem.

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by jbblache** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by jbblache** [comment]
recheck

**Comment by rahulsadanandan** [comment]
@jbblache Thank you for the pull request. We've incorporated it internally and it will roll out with the 3.86.x versions of xray.

**Comment by oumkale** [comment]
Hi @jbblache,

Kudos to you, Thank you so much for this PR.

We have released this in Xray version `3.86.1`.

**Pull request closed without merging**
