### PR TITLE
[artifactory] Add support for Ingress Class Name

### PR DESCRIPTION
**Pull request by rblaine95**
Add support for the `Ingress.spec.ingressClassName` field

#### PR Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] Chart Version bumped -- I'm not really certain what an appropriate version bump would be
- [x] CHANGELOG.md updated -- just need appropriate version
- [x] Title of the PR starts with chart name (e.g. `[artifactory]`)

**What this PR does / why we need it**:
This adds support for the `spec.ingressClassName` field in Ingresses, added in k8s 1.18, as the `ingress.class` annotation is, [depending on Ingress Controller](https://github.com/kubernetes/ingress-nginx/releases/tag/controller-v1.0.2), being [deprecated](https://kubernetes.io/docs/concepts/services-networking/ingress/#deprecated-annotation).

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: No issue has been raised.

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by rblaine95** [comment]
I have read the CLA Document and I hereby sign the CLA.

**Comment by rblaine95** [comment]
recheck

**Comment by chukka** [comment]
Thanks for the PR . we will take  this internally for review, test and plan this PR in next release of artifactory (mostly end of the month) if every thing looks good

**Comment by chukka** [comment]
@rblaine95 we already took this internally . This is planned for release  7.29.x  early next week  :)

**Comment by ArieLevs** [comment]
@chukka Thanks a lot!

**Comment by chukka** [comment]
Added as part of #1554 . closing this

**Pull request closed without merging**
