### PR TITLE
[artifactory]Fixed wrong cache-fs provider ID of cluster-s3-storage-v3 in the binarystore.xml 

### PR DESCRIPTION
**Pull request by lytravis**
fixes bug. links provider and chain for cache-fs.  Lines 172-175 would not work with current chart

#### PR Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] Chart Version bumped
- [ ] CHANGELOG.md updated
- [ ] Variables and other changes are documented in the README.md
- [ ] Title of the PR starts with chart name (e.g. `[artifactory]`)

**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Review by gitta-jfrog — APPROVED** [review]
Thanks, important fix!

**Comment by lytravis** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by chukka** [comment]
@lytravis This is taken internally and will be available in next artifactory 7.59.x patch release , Appreciate your time on this

**Comment by chukka** [comment]
Fixed via #1782

**Pull request closed without merging**
