### PR TITLE
Details on masterKey

### PR DESCRIPTION
**Pull request by gliptak**
https://stackoverflow.com/a/55113540/304690

### CODE REVIEW

**Comment by eldada** [comment]
Hi @gliptak . Thx for the PR. The CI failed as you did not update chart version. Please bump chart version in `Chart.yaml` and add entry in `CHANGELOG.md` explaining the change.
BTW - your StackOverflow link is Artifactory HA. This PR is distribution... is this intentional?

**Comment by gliptak** [comment]
@eldada thank you for the pointers. Updated. I'm not sure of that difference between HA and distribution ...

**Comment by eldada** [comment]
@gliptak - you have a mix up.
The changes in `stable/distribution/README.md` are for the *JFrog Distribution Helm Chart*. 
The changes in `stable/artifactory/CHANGELOG.md` and `stable/artifactory/Chart.yaml` are for the *JFrog Artifactory Helm Chart*.
These are two different charts to different products.
I think you mean to add the changes to the README of [Artifactory](https://github.com/jfrog/charts/tree/master/stable/artifactory) and [Artifactory HA](https://github.com/jfrog/charts/tree/master/stable/artifactory-ha) charts?

**Comment by gliptak** [comment]
@eldada updated

**Comment by eldada** [comment]
I did some digging to get the actual format of the master key string.
The official definition is: `A 128-Bit key size (hexadecimal encoded)`. Not just a 16 characters log string.
It can be generated with 
```
openssl rand -hex 16
```
 
So can you please update the description text to
```
Artifactory masterkey. A 128-Bit key size (hexadecimal encoded) string (32 hex characters). Can be generated with `openssl rand -hex 16`.
NOTE: This key can be generated only once and cannot be updated once created.
```

How does this sound?

**Comment by gliptak** [comment]
@eldada thank you for looking into this. I guess one cannot just type in a masterKey ... I updated as per above

**Pull request merged**
