### PR TITLE
Don't Merge [artifactory][artifactory-ha] Add gid support for artifactory statefulset

### PR DESCRIPTION
**Pull request by Amos-85**
#### PR Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] Chart Version bumped
- [x] CHANGELOG.md updated
- [x] Title of the PR starts with chart name (e.g. `[artifactory]`)

**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:
This PR should support group-id instead of using the the same number for uid & gid.  
There is some use cases we need to define different uid's & gid's.

### CODE REVIEW

**Comment by Amos-85** [comment]
Hi @rahulsadanandan  / @eldada ,
Can you please review the PR ?

**Comment by chukka** [comment]
@Amos-85  Thanks for the PR, Would you mind doing the same changes for artifactory-ha chart too in the same PR. 

Note : We will plan to merge this PR  to master along with artifactory 7.12.x release next week :)

**Review by eldada — APPROVED** [review]

**Comment by Amos-85** [comment]
@chukka  Done.

**Comment by chukka** [comment]
> @chukka,
> Done.

Appreciate it ! Please give us some time till next week for this to be merged

**Comment by Amos-85** [comment]
Ok @chukka,
by the way, is it possible the c_install_charts check has been stucked for some reason or it didn't run at all?

**Comment by chukka** [comment]
> Ok @chukka,
> by the way, is it possible the **c_install_charts** check has been stucked for some reason or it didn't run at all?

No, Generally it takes couple of hours to run all the tests under CI directory[here](https://github.com/Amos-85/jfrog-charts/tree/add_gid/stable/artifactory-ha/ci)

**Review by chukka — APPROVED** [review]

**Pull request merged**
