### PR TITLE
Added ingress annotation to avoid 413 errors.

### PR DESCRIPTION
**Pull request by joe-sonrichard**
#### PR Checklist
- [X] Chart Version bumped
- [X] CHANGELOG.md updated

**What this PR does / why we need it**:
Adds a recommended annotation to values.yaml to avoid 413 errors from the nginx ingress. For us, the ingress was rejecting files as small as 2 MB. 

Additional reading: 
 - https://www.cyberciti.biz/faq/linux-unix-bsd-nginx-413-request-entity-too-large/
 - https://www.jfrog.com/jira/browse/RTFACT-9030

### CODE REVIEW

**Comment by eldada** [comment]
Thx @joe-sonrichard for the contribution. Can I bother you to do 2 things?
1. Change the destination branch to be `inbound-from-forks`. We are now using a two stage contribution flow. Once merged, we'll take into `master`.
2. Add the same change to the `artifactory-ha` chart.

Thx!

**Comment by chukka** [comment]
@joe-sonrichard Thanks for the PR. Can you please do 2 things (as mentioned in above comment)?

Change the destination branch to be inbound-from-forks. We are now using a two stage contribution flow. Once merged, we'll take into master.
Add the same change to the artifactory-ha chart.

Thanks

**Comment by joe-sonrichard** [comment]
Yes I can make those changes. Sorry for the delay.

@eldada, I do not see a branch named `inbound-from-forks` when I try to change the branch I'm merging into. I do see `pre-unified-platform-inbound-from-forks` but If I merge there I'll also pull commits from master into it. Is there any chance `inbound-from-forks` is protected somehow?

Yes, I'll add that change to the artifactory-ha chart.

**Comment by joe-sonrichard** [comment]
@eldada & @chukka, here's what I can see when I try to change base to `inbound-from-forks`.
image

I'm guessing it's a permissions issue.

**Comment by chukka** [comment]
@joe-sonrichard Can you try now please

**Comment by eldada** [comment]
@joe-sonrichard - can you rebase again? We'll take into master for now as this is a change to a comment and resolve the fork branch issue.

**Comment by chukka** [comment]
Hi @joe-sonrichard Hope you can see `inbound-from-forks` branch now. Can you please 

1. Rebase and update your PR -final time :)
2. Change the destination branch to be inbound-from-forks. We are now using a two stage contribution flow. Once merged, we'll take into master

**Comment by joe-sonrichard** [comment]
As requested, I've rebased off the current master.

Per @eldada I've left the base as master though I'm happy to change if it it's decided that it should be `inbound-from-forks`. Also, I can now see that branch though I couldn't earlier so the fix was successful.

**Comment by chukka** [comment]
@joe-sonrichard Sorry for the confusion . Can you please rebase from `inbound-from-forks`.
Once merged to `inbound-from-forks` , we'll take into master 

Its pending from long time :)

**Comment by joe-sonrichard** [comment]
@chukka base changed.

**Pull request merged**
